# Netlify Build Settings for Next.js

[build]
  command = "npm run build"
  publish = ".next"

# Ensure environment variables are used for API keys and sensitive data
[build.environment]
  NODE_VERSION = "18"
  NEXT_PRIVATE_TARGET = "server"
  NETLIFY_NEXT_PLUGIN_SKIP = "false"

# Enable Netlify Next.js Plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirects for better URL handling
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache optimization to improve build speed
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

